<?php
include 'templates/layout/header.phtml';
?>

<div class="container mt-4">
  <h2 class="mb-4 text-center">Lista de Marcas</h2>
    <div class="d-flex justify-content-center align-items-center flex-wrap gap-3">
      <?php foreach ($marcas as $marca): ?>
        <a href="<?= BASE_URL ?>marca/<?= (int)$marca->marca_id ?>"
           class="text-decoration-none text-dark">
          <div class="card text-center shadow-sm" style="width: 180px;">
            <div class="card-body d-flex flex-column justify-content-center align-items-center">
              <h5 class="card-title fw-bold mb-0">
                <?= htmlspecialchars($marca->marca) ?>
              </h5>
            </div>
          </div>
        </a>
      <?php endforeach; ?>
    </div>
</div>

<?php
include 'templates/layout/footer.phtml';