<?php
include 'templates/layout/header.phtml'; ?> <div class="container mt-4">
    <h2 class="mb-4 text-center">A D M I N</h2>
    <div class="row g-3">
        <div class="col-12 col-sm-6 col-md-4 col-lg-3"> <a href="adminMarcas" class="text-decoration-none text-dark" style="display:block" title="Ver suplemento">
                <div class="card-body">
                    <h5 class="card-title mb-1"> <strong>Administrar Marcas</strong> </h5>
                </div>
        </div> </a>
    </div>
    <div class="col-12 col-sm-6 col-md-4 col-lg-3"> <a href="adminSuplementos" class="text-decoration-none text-dark" style="display:block" title="Ver suplemento">
            <div class="card-body">
                <h5 class="card-title mb-1"> <strong>Administrar Suplementos</strong> </h5>
            </div>
    </div> </a>
</div>
</div>
</div> <?php include 'templates/layout/footer.phtml';
